---
name: setuptools-wrapper
version: "{{major}}.{{minor}}.{{patch}}"
description: A simple interface to setuptools's setup function.
requirements:
  - setuptools
dev_requirements:
  - types-setuptools
classifiers:
  - "Topic :: Software Development :: Build Tools"
